functionsDirectory = "/Users/sebastianhurtado/Desktop/GetSellersClaude/jira-ai-scrum/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/sebastianhurtado/Desktop/GetSellersClaude/jira-ai-scrum/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/sebastianhurtado/Desktop/GetSellersClaude/jira-ai-scrum/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/jira/*"
to = "/.netlify/functions/jira-proxy"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/anthropic/*"
to = "/.netlify/functions/anthropic-proxy"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/twilio/*"
to = "/.netlify/functions/twilio-proxy"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/meta/*"
to = "/.netlify/functions/meta-proxy"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]